### PR TITLE
update to tideways

### PR DESCRIPTION
**Pull request by glaubinix**
Uses tideways instead of qafoo classes

### CODE REVIEW

**Comment by glaubinix** [comment]
@till I cant assign PRs here :) Can you still have a look?

**Comment by till** [comment]
@glaubinix I gave you access, what do you think if we add this also:

```
ini_set('tideways.framework', 'zf1');
```

We could remove all the code where we built routes? Or we make it optional...? Like, if the ini var is not empty, we use our code, otherwise we let them build routes?

**Comment by glaubinix** [comment]
@till do you mean like this?

**Comment by till** [comment]
@glaubinix yeah! Should I merge?

**Comment by glaubinix** [comment]
yes, please

**Pull request merged**
